### PR TITLE
Improve compatibility from symfony 2.3.6 to ~2.5.0

### PR DESCRIPTION
**Pull request by jubianchi**
Improving compatibility through symfony versions (from 2.3 to 2.5)

This is a bit hacky at the moment, especially [here](https://github.com/hoaproject/Contributions-Symfony-BenchBundle/pull/4/files#diff-1) but for now I just duplicated hacks from `Symfony\Component\Console\Helper\TableHelper`.

This is a first step. To get things clean, I have to:
- [ ] see how we can draw tables with `hoa/Console` (ping @Hywan)
- [ ] port the feature to the `hoathis/symfony-console-bridge` library
- [ ] wire the `hoathis/bench-bundle` and the `hoathis/symfony-console-bridge` together
- [ ] draw tables from there, getting rid of Symfony closed implementation

### CODE REVIEW

**Comment by jubianchi** [comment]
> see how we can draw tables with hoa/Console (ping @Hywan)

Seems impossible to draw table like the following with `hoa/console`:

```
+------+-----------------+-----------------+
| Mark | Time            | Percent         |
+------+-----------------+-----------------+
| foo  | 4.0034830570221 | 100             |
| bar  | 2.001620054245  | 49.996965785434 |
+------+-----------------+-----------------+
```

I looked at `Hoa\Console\Chrome\Text::columnize`. 
@Hywan if you confirm that drawing full-decorated table is not yet possible I propose we merge this PR for now and improve both `hoa/console`, `hoathis/symfony-console-bridge` and `hoathis/bench-bundle` later.

**Comment by Hywan** [comment]
You can draw such a table but I don't know with such a style. Will take a try soon.

**Comment by Hywan** [comment]
ping?

**Comment by jubianchi** [comment]
@Hywan pong!

**Comment by Hywan** [comment]
State of this PR?

**Comment by jubianchi** [comment]
@Hywan still waiting your feedback:

> @jubianchi > @Hywan if you confirm that drawing full-decorated table is not yet possible I propose we merge this PR
> 
> @Hywan > You can draw such a table but I don't know with such a style. Will take a try soon.

**Comment by Hywan** [comment]
Did you check the `columize` method inside the `Hoa\Console` library?

**Comment by jubianchi** [comment]
@Hywan yep, it does not allow us to draw such tablees with headers and cells having a diferent layout.

It only draw columns like its name says :)

**Comment by Hywan** [comment]
Ok, so it's not possible ;-).

**Comment by jubianchi** [comment]
@Hywan  ok thanks for the feedback. I'll merge it as is and we'll get to it later.

**Comment by Hywan** [comment]
:+1:

**Comment by Hywan** [comment]
\o/

**Pull request merged**
